server.port=8081
spring.application.name=aula03

spring.datasource.url=jdbc:postgresql://localhost:5432/aula
spring.datasource.password=987654321
spring.datasource.username=postgres

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=true