spring.application.name=aula02

# configurações do hibernate para qual banco ele vai conectar
spring.datasource.url=jdbc:postgresql://localhost:5432/aula
spring.datasource.username=postgres
spring.datasource.password=987654321

# configurações do hibenate para recriar o banco de dados
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true

application.saudacao=ola