spring.application.name=aula05

#spring.h2.console.enabled=true
spring.datasource.url=jdbc:postgresql://localhost:5432/aula
spring.datasource.username=postgres
spring.datasource.password=987654321

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true